### ISSUE TITLE
Adding local chapter's GitHub account to the R-Ladies team

### ISSUE THREAD

**Issue by rladies-eastlansing** [rladies/meetup-presentations_east-lansing#1]
Hi @hfrick 
Could this @rladies-eastlansing account be added to the R-Ladies member team as well? That way, contributions to the Meetup/other repositories would be more convenient. @jananiravi is already there but since we'd be using this account to host a webpage/blog and other resources, this might make things easier. Thank you! 😃

**Comment by jananiravi** [comment]
Created an organizational account instead for @rladies-eastlansing (github.com/rladies-eastlansing) and added @jananiravi and @archerc5 as individual contributors instead based on @hfrick's suggestion on slack. 👍
